# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b7af8ab6ecc9620c1bf10ee934a5103cbc07ce2f935e4fd17a90e048c5df3e3e3ed3f0866aee20240b063e2c5182128f940dd7bce1eede7c623e93ff9a297b

test:
  secret_key_base: 3686726a8cfa370cbd19632e68b2a51f52cc73ffa8487af2deb2a621576fd93f8e097b234d7ace96290c32ba4fdd80bad6039f6bcc8ff07dc89f5508c7a13ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
